app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)


from app.main import routes

app/main/routes.py
import random
from flask import (render_template, request,
                   redirect, url_for, jsonify, flash, session)
from app.main import bp
from app.models import Flashcard
from flask_login import current_user, login_required, logout_user
from app.models import db, Score
from datetime import datetime


@bp.route('/help')
def help():
    if current_user.is_authenticated:
        return render_template('main/help.html', username=current_user.username)
    
    else:
        return render_template('main/help.html', username=None)

@bp.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    per_page = 7
    pagination = Flashcard.query.paginate(page=page, per_page=per_page)
    flashcards = pagination.items

    if current_user.is_authenticated:
        return render_template('main/index.html',
                               username=current_user.username,
                               flashcards=flashcards,
                               pagination=pagination)
    else:
        return render_template('main/index.html', 
                               username=None,
                               flashcards=flashcards,
                               pagination=pagination)
    

@bp.route('/add_word', methods=['GET', 'POST'])
@login_required
def add_word():
    if request.method == 'POST':
        question = request.form['question']
        answer = request.form['answer']
        flashcard = Flashcard(question=question, answer=answer)
        db.session.add(flashcard)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('main/add_word.html', username=current_user.username)


@bp.route('/study', methods=['GET'])
def study():
    all_words = Flashcard.query.all()
    total_words = len(all_words)
    
    # Сохраняем общее количество слов в сессии
    session['total_words'] = total_words
    
    # Получаем текущий индекс слова из сессии
    current_index = session.get('current_index', 0)
    
    if current_index >= total_words:
        return redirect(url_for('main.finish'))
    
    # Получаем текущее слово по индексу
    flashcard = all_words[current_index]
    
    question = flashcard.question
    correct_answer = flashcard.answer
    
    all_answers = [word.answer for word in Flashcard.query.filter(Flashcard.question != question).all()]
    wrong_answers = random.sample(all_answers, 2)
    
    answer_options = [correct_answer] + wrong_answers
    random.shuffle(answer_options)
    
    # Сохраняем текущий индекс в сессии
    session['current_index'] = current_index + 1
    
    return render_template('study/study.html', question=question, options=answer_options, 
                           correct_answer=correct_answer, total_words=total_words,
                           total_correct=session.get('total_correct', 0), 
                           current_index=current_index + 1, username=current_user.username)

    
@bp.route('/check_answer', methods=['POST'])
def check_answer():
    selected_answer = request.form['answer']
    correct_answer = request.form['correct_answer']
    
    if selected_answer == correct_answer:
        session['total_correct'] = session.get('total_correct', 0) + 1
        flash('Correct!', 'success')
    else:
        flash('Incorrect!', 'danger')
    
    return redirect(url_for('main.study'))
    
@bp.route('/finish', methods=['GET'])
def finish():
    total_words = session.get('total_words', 0)
    total_correct = session.get('total_correct', 0)

    if total_words > 0:
        percentage = round((total_correct / total_words) * 100)
        message = f'{percentage}% of correct answers ({total_correct}/{total_words})'
    else:
        message = "No words to evaluate"

    # Сохраняем результаты в сессии
    session['finish_message'] = message

    return render_template('study/finish.html',
                           message=message,
                           username=current_user.username)


@bp.route('/reset_session', methods=['GET'])
def reset_session():
    # Получаем результаты из сессии
    total_correct = session.get('total_correct', 0)
    # Создаем новую запись в таблице Score
    new_score = Score(user_id=current_user.id, date=datetime.now(), total_correct=total_correct)
    db.session.add(new_score)
    db.session.commit()
    # Сбрасываем данные из сессии, кроме информации о пользователе
    session.pop('current_index', None)
    session.pop('total_correct', None)
    
    # Перенаправляем пользователя на главную страницу
    return redirect(url_for('main.index'))


@bp.route('/check-word', methods=['GET'])
def check_word():
    word = request.args.get('word')
    if Flashcard.query.filter_by(question=word).first() or Flashcard.query.filter_by(answer=word).first():
        return jsonify({'exists': True})
    else:
        return jsonify({'exists': False})
    
    
@bp.route('/study_reverse', methods=['GET'])
def study_reverse():
    all_words = Flashcard.query.all()
    total_words = len(all_words)
    
    session['total_words'] = total_words
    current_index = session.get('current_index', 0)
    
    if current_index >= total_words:
        return redirect(url_for('main.finish'))
    
    flashcard = all_words[current_index]
    
    # Меняем местами question и answer
    question = flashcard.answer
    correct_answer = flashcard.question
    
    all_answers = [word.question for word in Flashcard.query.filter(Flashcard.answer != correct_answer).all()]
    wrong_answers = random.sample(all_answers, 2)
    
    answer_options = [correct_answer] + wrong_answers
    random.shuffle(answer_options)
    
    session['current_index'] = current_index + 1
    
    return render_template('study/study.html',
                           question=question,
                           options=answer_options,
                           correct_answer=correct_answer,
                           total_words=total_words,
                           total_correct=session.get('total_correct', 0), 
                           current_index=current_index + 1,
                           username=current_user.username)


@bp.route('/flashcards/delete/<int:word_id>', methods=['DELETE'])
def delete_word(word_id):
    word = Flashcard.query.get(word_id)
    if word:
        db.session.delete(word)
        db.session.commit()
        return jsonify({'message': 'Слово успешно удалено'})
    return jsonify({'error': 'Слово не найдено'}), 404

app/templates/main/add_word.html
{% extends 'base.html' %}

{% block title %}Add Word{% endblock %}

{% block content %}
<section class="section custom-container">
<div class="container">
    <h1 class="title">Add a New Word</h1>
    <form action="{{ url_for('main.add_word') }}" method="post" id="add-form" class="form">
        <div class="field">
            <label for="question" class="label">Question:</label>
            <div class="control">
                <input type="text" name="question" class="input" id="question" required onInput="checkWordExists('question')">
                <div class="invalid-feedback" id="question-feedback"></div>
            </div>
        </div>
        <div class="field">
            <label for="answer" class="label">Answer:</label>
            <div class="control">
                <input type="text" name="answer" class="input" id="answer" required onInput="checkWordExists('answer')">
                <div class="invalid-feedback" id="answer-feedback"></div>
            </div>
        </div>
        <div class="field">
            <div class="control">
                <button type="submit" class="button is-primary" id="submit-btn" disabled>Add</button>
            </div>
        </div>
    </form>
</div>
</section>
{% endblock %}

app/templates/main/help.html
{% extends 'base.html' %}

{% block title %}Help{% endblock %}

{% block content %}
<section class="section custom-container">
    <div class="container">
        <h1 class="title">Help</h1>
        <ul class="learning-scores">
            
                <li class="box score-item">
                    <p><strong>Flashcards: </strong>
                        Flash cards are suitable for studying and testing knowledge on any topic
                    </p>
                    <p><strong>Profile: </strong>
                        Test results are entered into the profile of each user with date and time
                    </p>
                    <p><strong>Add word: </strong>
                        You can add words and expressions.
                        Question first
                        Then the answer
                    </p>
                    <p><strong>Stydy: </strong>
                        Check of knowledge. The question is given three possible answers - one of them is correct.
A record of correct answers is kept
                    </p>

                    <p><strong>Study revers: </strong>
                        You can study words and expressions in reverse order.
                        Answer first
                        Then the question
                    </p>
                    <p><strong>Reset session: </strong>
                        Training can be started again if all words have been checked. Click on the REset Session button
                    </p>
                </li>
        </ul>
    </div>   
    <div class="container">
        <h1 class="title">Помощь</h1>
        <ul class="learning-scores">
                <li class="box score-item">
                    <p><strong>Флэшкарты: </strong>
                        Карточки (флеш-карты) подходят для изучения и тестирования знаний по любой теме.

                    </p>
                    <p><strong>Порофиль: </strong>
                        Результаты тестов записываются в профиль каждого пользователя с указанием даты и времени.
                    </p>
                    <p><strong>Добавить слово: </strong>
                        Вы можете добавлять слова и выражения. Сначала вопрос, затем ответ.
                    </p>
                    <p><strong>Обучение: </strong>
                        Проверка знаний. Дается вопрос с тремя вариантами ответов - один из них правильный. Ведется учет правильных ответов.
                    </p>

                    <p><strong>Обучение наоборот: </strong>
                        Вы можете изучать слова и выражения в обратном порядке. Сначала ответ, затем вопрос.
                    </p>
                    <p><strong>Начать заново: </strong>
                        Обучение можно начать заново, если все слова были проверены. Нажмите кнопку "Сбросить сессию".
                    </p>
                </li>
        </ul>
    </div>
    
</section>
{% endblock %}

app/templates/main/index.html
{% extends 'base.html' %}

{% block title %}Flashcards - Home{% endblock %}

{% block content %}
<section class="section custom-container">
    <h2 class="title">Flashcards</h2>
    <div class="container">
        <div class="box">
            <table class="table is-striped is-hoverable is-fullwidth">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Question</th>
                        <th>Answer</th>
                        <th>Action</th> <!-- Добавлен заголовок для кнопки "Удалить" -->
                    </tr>
                </thead>
                <tbody>
                    {% for card in flashcards %}
                    <tr id="word_{{ card.id }}"> <!-- Добавлен идентификатор для каждой строки слова -->
                        <td>{{ loop.index + (pagination.page - 1) * pagination.per_page }}</td>
                        <td>{{ card.question }}</td>
                        <td>{{ card.answer }}</td>
                        <td>
                            <button onclick="deleteWord({{ card.id }})" class="button delete-word-btn">delete</button> <!-- Добавлена кнопка "Удалить" -->
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <nav class="pagination is-centered" role="navigation" aria-label="pagination">
                <div class="pagination-previous-next">
                    {% if pagination.has_prev %}
                    <a href="{{ url_for('main.index', page=pagination.prev_num) }}" class="pagination-previous">Previous</a>
                    {% endif %}
                    {% if pagination.has_next %}
                    <a href="{{ url_for('main.index', page=pagination.next_num) }}" class="pagination-next">Next</a>
                    {% endif %}
                </div>
            </nav>
        </div>

        {% if finish_message %}
        <div class="notification is-info">{{ finish_message }}</div>
        {% endif %}
    </div>
</section>
{% endblock %}